# project properties
project.name=openrndr-template
project.group=org.openrndr
project.version=1.0.0

# the main class of the application, used for packaging and running from Gradle
applicationMainClass=TemplateProgramKt

# set to true to enable OPENRNDR specific tasks
openrndr.tasks=true

# set to true to enable the use of snapshots from the Sonatype snapshots repository
openrndr.allowSonatypeSnapshots=false

# set to true to enable the use of locally built OPENRNDR and ORX dependencies from your local Maven repository
openrndr.allowLocalSnapshots=false
kotlin.code.style=official
#org.gradle.configuration-cache=true
#org.gradle.configuration-cache.parallel=true
#org.gradle.configuration-cache.problems=warn
