project.name=openrndr-template
project.group=org.openrndr
project.version=1.0.0
applicationMainClass=TemplateProgramKt
openrndr.tasks=true
openrndr.allowSonatypeSnapshots=true
openrndr.allowLocalSnapshots=false
kotlin.code.style=official
#org.gradle.configuration-cache=true
#org.gradle.configuration-cache.parallel=true
#org.gradle.configuration-cache.problems=warn

